### ISSUE TITLE
哥 请问你能不能写一个在react组件里调用的用例？

### ISSUE THREAD

**Issue by ManuRodgers** [DiamondYuan/dva-model-creator#1]
![image](https://user-images.githubusercontent.com/33333844/58852006-17b05200-86d8-11e9-96f0-bb2e7b951b8d.png)

哥 这里我在mapStateToProps 这个方法里拿到的counter是any类型， 请问怎么把这里弄成ICounter 的这个counter这个状态的类型

**Comment by DiamondYuan** [comment]
https://github.com/umijs/umi-examples/tree/master/typescript

**Comment by DiamondYuan** [comment]
看这里

https://github.com/umijs/umi-examples/blob/c314b6c2ce3251ef3bd5be18943b936f24224ae1/typescript/src/pages/index.tsx#L13
