### ISSUE TITLE
兼容ts 3.6？

### ISSUE THREAD

**Issue by zhanba** [DiamondYuan/dva-model-creator#13]
目前报了好多错误

**Comment by DiamondYuan** [comment]
https://github.com/DiamondYuan/dva-model-creator/blob/master/package.json


项目的 ts 我升级到了 3.6 并没有遇到错误。

**Comment by DiamondYuan** [comment]
的确有问题，我研究一下。

**Comment by DiamondYuan** [comment]
更新到最新版本吧。
