### ISSUE TITLE
antd pro v5, 过不了 ModelValidate

### ISSUE THREAD

**Issue by lei-cao** [DiamondYuan/dva-model-creator#22]
之前用的 antd pro v3 在src/models 里用，没问题。 最近搞到了 v5，但是在page下面的model使用，model validate 过不了。 需要skipModelValidate 才能加载model

**Comment by DiamondYuan** [comment]
这个是 umi 的问题

**Comment by DiamondYuan** [comment]
https://umijs.org/zh-CN/plugins/plugin-dva#%E6%88%91%E7%9A%84-model-%E5%86%99%E6%B3%95%E5%BE%88%E5%8A%A8%E6%80%81%EF%BC%8C%E4%B8%8D%E8%83%BD%E8%A2%AB%E8%AF%86%E5%88%AB%E5%87%BA%E6%9D%A5%E6%80%8E%E4%B9%88%E5%8A%9E%EF%BC%9F
