### ISSUE TITLE
考虑repo合并？

### ISSUE THREAD

**Issue by nnuzi** [DiamondYuan/dva-model-creator#3]
[dva-utils](https://github.com/Tommy-White/dva-utils) 主旨抽象dva项目中各种pattern，达到减少模版代码，提高使用安全性与可读性。

**Comment by DiamondYuan** [comment]
我早上就在思考这个问题。让我再思考一下怎么合并。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/60228681-0d900680-98c6-11e9-8d4f-1e3c246c6320.png)


![image](https://user-images.githubusercontent.com/9692408/60228694-154fab00-98c6-11e9-95f1-538a416bbe10.png)

![image](https://user-images.githubusercontent.com/9692408/60228707-1f71a980-98c6-11e9-832d-d753e2169ff3.png)






@Tommy-White  虽然 dva-utils 很爽。但是就失去了一些信息。

比如我上面这个 action。根据 ID 来获取列表数据。一眼就可以看到修改的参数是哪些。
而使用 merge 的话，就失去了这个信息。

**Comment by nnuzi** [comment]
@DiamondYuan 
稍晚我会细看下此repo。
此外此会考虑逐步抽象提供构建在dva( react、redux、redux-saga 等 )的程序实用功能和常见模式

**Comment by DiamondYuan** [comment]
> @DiamondYuan
> 稍晚我会细看下此repo。
> 此外此会考虑逐步抽象提供构建在dva( react、redux、redux-saga 等 )的程序实用功能和常见模式

actionCreatorFactory 代码是从别的地方拷贝过来的
https://github.com/aikoven/typescript-fsa

**Comment by DiamondYuan** [comment]
> @DiamondYuan
> 稍晚我会细看下此repo。
> 此外此会考虑逐步抽象提供构建在dva( react、redux、redux-saga 等 )的程序实用功能和常见模式

真实场景的项目 https://github.com/DiamondYuan/vanaheim/tree/master/packages/vanaheim-website
