### ISSUE TITLE
如何与dva-immer一同食用？

### ISSUE THREAD

**Issue by capdiem** [DiamondYuan/dva-model-creator#4]
[dva-immer](https://github.com/dvajs/dva/tree/master/packages/dva-immer) umi+dva开启了immer配置

**Comment by DiamondYuan** [comment]
> [dva-immer](https://github.com/dvajs/dva/tree/master/packages/dva-immer) umi+dva开启了immer配置

暂时不支持。我今天升级一下。

**Comment by DiamondYuan** [comment]
最新版本已经支持
