### ISSUE TITLE
考虑整合typescript-fsa-redux-saga吗？

### ISSUE THREAD

**Issue by zhanba** [DiamondYuan/dva-model-creator#5]

**Comment by DiamondYuan** [comment]
saga 本身就支持的啊。

takeEvery 就好了。

**Comment by DiamondYuan** [comment]
不考虑支持了。typescript-fsa-redux-saga 只是省了 xxx.start 以及 put(xxx.done())。
而且 dva 本身 return 有其他的含义。会冲突。

**Comment by zhanba** [comment]
主要是`bindAsyncAction`，可以少些一些action

**Comment by DiamondYuan** [comment]
> 主要是`bindAsyncAction`，可以少些一些action

asyncAction 现在就是支持的



![image](https://user-images.githubusercontent.com/9692408/60878668-b51c1a00-a272-11e9-96d2-e8a7af1c7fd6.png)

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/60878744-ebf23000-a272-11e9-9b19-030f687b42b0.png)


集成以后代码也只能简化成这个样子

**Comment by zhanba** [comment]
其实我希望有个类似这种的api，一步就把简单的请求做完。不过感觉有点过度封装。。

```ts
export function takeAsyncAction<P, S, E>(
  action: ActionCreator<P>,
  asyncAction: AsyncActionCreators<P, S, E>,
  asyncCall: (p: P) => AxiosPromise<S>
) {
  const worker = bindAsyncAction(asyncAction)(function*(params): SagaIterator {
    const res: AxiosResponse<S> = yield call(asyncCall, params)
    return res.data
  })

  function* saga(sagaAction: Action<P>): SagaIterator {
    yield fork(worker, sagaAction.payload)
  }

  return takeEvery(action, saga)
}
```
