### ISSUE TITLE
yield put 告警

### ISSUE THREAD

**Issue by sonacy** [DiamondYuan/dva-model-creator#7]
```js
const actionCreate = actionCreatorFactory('base')
export const updateBase = actionCreate<Partial<IGlobal>>('updateBase')
export const getProducts = actionCreate('getProducts')

const model = new DvaModelBuilder<IGlobal>(
  {
    products: [],
    curAppId: null,
  },
  'base',
)
  .case(updateBase, (state, payload) => ({
    ...state,
    ...payload,
  }))
  .takeEvery(getProducts, function*(_, { call, put, select }) {
    let curAppId = yield select<IState>((state) => state.base.curAppId)
    const data = yield call(fetchProducts)
    if (!curAppId) {
      curAppId = data[0].app_id
    }
    yield put(
      updateBase({
        curAppId,
        products: data,
      }),
    )
  })
  .build()
```
Warning: [sagaEffects.put] base/updateBase should not be prefixed with namespace base

看上去model内部调用action返回的type不该加上namespace，是否在action调用的时候提供个可选项，可以不返回prefix？

**Comment by DiamondYuan** [comment]
> ```js
> const actionCreate = actionCreatorFactory('base')
> export const updateBase = actionCreate<Partial<IGlobal>>('updateBase')
> export const getProducts = actionCreate('getProducts')
> 
> const model = new DvaModelBuilder<IGlobal>(
>   {
>     products: [],
>     curAppId: null,
>   },
>   'base',
> )
>   .case(updateBase, (state, payload) => ({
>     ...state,
>     ...payload,
>   }))
>   .takeEvery(getProducts, function*(_, { call, put, select }) {
>     let curAppId = yield select<IState>((state) => state.base.curAppId)
>     const data = yield call(fetchProducts)
>     if (!curAppId) {
>       curAppId = data[0].app_id
>     }
>     yield put(
>       updateBase({
>         curAppId,
>         products: data,
>       }),
>     )
>   })
>   .build()
> ```
> 
> Warning: [sagaEffects.put] base/updateBase should not be prefixed with namespace base
> 
> 看上去model内部调用action返回的type不该加上namespace，是否在action调用的时候提供个可选项，可以不返回prefix？

升级到最新版本的 dva。 增加一个配置 namespacePrefixWarning

```
export const dva = {
  config: {
    namespacePrefixWarning: false,
    onError(err) {
      err.preventDefault();
      console.log(err);
    },
  },
};
```


或者使用 removeActionNamespace 函数。

```
import { DvaModelBuilder, removeActionNamespace } from 'dva-model-creator';
builder.subscript(({ dispatch }) => {
  dispatch(removeActionNamespace(xxxxx.started()));
});
```
